REPOSITORIES:
  - wp-mu-plugins
  - wp-theme-2018
  - wp-plugin-epfl-coming-soon
  - wordpress.plugin.tequila
  - wp-plugin-epfl-settings
  - wp-plugin-epfl-remote-content
  - wp-plugin-epfl-content-filter
  - wp-plugin-enlighter
  - wp-plugin-epfl-intranet
  - wp-plugin-epfl-library
  - wp-plugin-epfl-diploma-verification
  - wp-plugin-epfl-partner-universities
  - wp-plugin-epfl-404
  - wp-gutenberg-epfl
  - wp-plugin-epfl-courses-se
  - wp-plugin-epfl-restauration
  - wp-plugin-epfl-cache-control
  - wordpress.plugin.accred
  - wp-plugin-epfl-translate
  - wp-plugin-epfl-menus
  - wp-plugin-pushgateway
  - wp-ops
DEBUG: true
NAMESPACE: "svc0041t-wordpress"
